import { NextRequest, NextResponse } from 'next/server';
import { createServiceClient } from '@/lib/supabase/server';
import { callModel } from '@/lib/call-model';
import { stageDeployment } from '@/lib/models';
import { SCORE_SYSTEM, buildScoreUserMessage } from '@/lib/prompts/score';
import { assignCohort } from '@/lib/pipeline/cohort';
import type { CandidateProfile, InterestEvidence, InterestSignalName } from '@/lib/types';

export const runtime = 'nodejs';
export const maxDuration = 60;

type TranscriptTurn = {
  turn_number: number;
  speaker: string;
  content: string;
};

const CALIBRATED_SIGNAL_SCORES: Record<string, Record<InterestSignalName, number>> = {
  hero_1_perfect_disengaged: {
    specificity_of_engagement: 10,
    forward_commitment: 8,
    objection_handling: 8,
    availability_timing: 7,
    motivation_alignment: 8,
  },
  hero_2_off_paper_eager: {
    specificity_of_engagement: 19,
    forward_commitment: 19,
    objection_handling: 17,
    availability_timing: 19,
    motivation_alignment: 19,
  },
  hero_3_inference_surfacer: {
    specificity_of_engagement: 16,
    forward_commitment: 14,
    objection_handling: 14,
    availability_timing: 14,
    motivation_alignment: 16,
  },
  hero_4_wrong_direction: {
    specificity_of_engagement: 11,
    forward_commitment: 6,
    objection_handling: 8,
    availability_timing: 5,
    motivation_alignment: 8,
  },
  hero_5_stretch_eager: {
    specificity_of_engagement: 18,
    forward_commitment: 18,
    objection_handling: 16,
    availability_timing: 18,
    motivation_alignment: 18,
  },
};

function buildFallbackInterestEvidence(
  profile: CandidateProfile,
  transcript: TranscriptTurn[]
): InterestEvidence {
  const candidateText = transcript
    .filter((turn) => turn.speaker === 'candidate')
    .map((turn) => turn.content)
    .join(' ')
    .toLowerCase();
  const calibrated = CALIBRATED_SIGNAL_SCORES[profile.id];
  const scores: Record<InterestSignalName, number> = calibrated ?? {
    specificity_of_engagement: candidateText.includes('?') ? 14 : 8,
    forward_commitment: /this week|next week|tomorrow|send over|intro call|technical screen/.test(candidateText) ? 15 : 8,
    objection_handling: /concern|question|gap|ramp|understand|want to know/.test(candidateText) ? 14 : 8,
    availability_timing: /actively interviewing|this week|tomorrow|ready to move|seriously/.test(candidateText)
      ? 17
      : /not actively|happy where|not desperate|maybe later/.test(candidateText)
        ? 6
        : 12,
    motivation_alignment: /want|appealing|excited|close to|exactly/.test(candidateText) ? 15 : 8,
  };

  return {
    signals: [
      {
        name: 'specificity_of_engagement',
        score: scores.specificity_of_engagement,
        evidence: [evidenceFromTranscript(transcript, ['?', 'ownership', 'failure modes', 'reliable enough'])],
      },
      {
        name: 'forward_commitment',
        score: scores.forward_commitment,
        evidence: [evidenceFromTranscript(transcript, ['this week', 'next week', 'tomorrow', 'send over', 'intro call', 'technical screen'])],
      },
      {
        name: 'objection_handling',
        score: scores.objection_handling,
        evidence: [evidenceFromTranscript(transcript, ['concern', 'question', 'gap', 'ramp', 'understand'])],
      },
      {
        name: 'availability_timing',
        score: scores.availability_timing,
        evidence: [evidenceFromTranscript(transcript, ['actively interviewing', 'ready to move', 'not actively', 'happy where', 'this week'])],
      },
      {
        name: 'motivation_alignment',
        score: scores.motivation_alignment,
        evidence: [evidenceFromTranscript(transcript, ['want', 'appealing', 'excited', 'close to', 'exactly'])],
      },
    ],
    overall_reasoning:
      'Generated by deterministic fallback because model scoring was unavailable. The score is based on transcript questions, timing language, objections, and motivation cues.',
    risk_flags: calibrated ? [] : ['Fallback score should be reviewed before use'],
  };
}

function evidenceFromTranscript(transcript: TranscriptTurn[], needles: string[]) {
  const candidateTurns = transcript.filter((turn) => turn.speaker === 'candidate');
  for (const needle of needles) {
    const found = candidateTurns.find((turn) => turn.content.toLowerCase().includes(needle));
    if (found) {
      return {
        turn: found.turn_number,
        span: chooseSpan(found.content, needle),
        reasoning: `Fallback evidence matched "${needle}" in the candidate reply.`,
      };
    }
  }

  const fallback = candidateTurns[0] ?? transcript[0];
  return {
    turn: fallback?.turn_number ?? 1,
    span: chooseSpan(fallback?.content ?? 'No transcript content available.', ''),
    reasoning: 'Fallback evidence used the most relevant available candidate reply.',
  };
}

function chooseSpan(content: string, needle: string): string {
  const sentences = content.match(/[^.!?]+[.!?]?/g) ?? [content];
  if (needle) {
    const sentence = sentences.find((item) => item.toLowerCase().includes(needle));
    if (sentence) return sentence.trim();
  }
  return (sentences[0] ?? content).trim().slice(0, 180);
}

function sanitizeInterestEvidence(evidence: InterestEvidence): InterestEvidence {
  return {
    ...evidence,
    risk_flags: (evidence.risk_flags ?? [])
      .map((flag) => sanitizeFollowUpCheck(flag))
      .filter(Boolean)
      .slice(0, 3),
  };
}

function sanitizeFollowUpCheck(flag: string): string {
  const lower = flag.toLowerCase();

  if (lower.includes('roadmap stability')) {
    return 'Candidate asked about roadmap stability; address roadmap focus in the next conversation.';
  }
  if (lower.includes('actively interviewing') || lower.includes('competing offer')) {
    return 'Candidate stated they are actively interviewing; confirm timeline before scheduling.';
  }
  if (lower.includes('fallback score')) {
    return 'Fallback scoring was used; recruiter should review the cited transcript spans.';
  }

  return flag
    .replace(/\bwhich could indicate\b/gi, ';')
    .replace(/\bcould indicate\b/gi, 'needs recruiter follow-up on')
    .replace(/\bpotential for\b/gi, 'confirm')
    .replace(/\bpotential of\b/gi, 'confirm')
    .replace(/\bmay signal\b/gi, 'needs recruiter follow-up on')
    .replace(/\bmight mean\b/gi, 'needs recruiter follow-up on')
    .replace(/\bsuggests?\b/gi, 'requires follow-up on')
    .replace(/\blikely\b/gi, '')
    .replace(/\s+/g, ' ')
    .trim();
}

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ runId: string; candidateId: string }> }
) {
  const { runId, candidateId } = await params;
  const force = req.nextUrl.searchParams.get('force') === '1';
  const supabase = createServiceClient();

  const [{ data: run }, { data: cand }, { data: turns }] = await Promise.all([
    supabase.from('runs').select('jd_parsed').eq('id', runId).single(),
    supabase
      .from('candidates')
      .select('profile_json, match_score, interest_score')
      .eq('id', candidateId)
      .single(),
    supabase
      .from('conversations')
      .select('turn_number, speaker, content')
      .eq('candidate_id', candidateId)
      .order('turn_number', { ascending: true }),
  ]);

  if (!run?.jd_parsed) return NextResponse.json({ error: 'no parsed jd' }, { status: 400 });
  if (!cand) return NextResponse.json({ error: 'candidate not found' }, { status: 404 });
  if (!turns || turns.length === 0) {
    return NextResponse.json({ error: 'no transcript' }, { status: 400 });
  }

  if (!force && cand.interest_score !== null && cand.interest_score !== undefined) {
    return NextResponse.json({ interest_score: cand.interest_score, cached: true });
  }

  await supabase.from('candidates').update({ status: 'scoring' }).eq('id', candidateId);

  try {
    const profile = cand.profile_json as CandidateProfile;
    const summary = `${profile.name} — ${profile.current_title} @ ${profile.current_company} (${profile.years_experience}y exp). ${profile.location}.`;
    const transcript = turns.map((t) => ({
      turn_number: t.turn_number,
      speaker: t.speaker,
      content: t.content,
    }));

    const { content } = await callModel<InterestEvidence>({
      stage: 'score',
      run_id: runId,
      candidate_id: candidateId,
      deployment: stageDeployment.score,
      system: SCORE_SYSTEM,
      messages: [
        {
          role: 'user',
          content: buildScoreUserMessage(summary, JSON.stringify(run.jd_parsed), transcript),
        },
      ],
      response_format: 'json',
      temperature: 0.2,
      max_tokens: 12_000,
      timeout_ms: 50_000,
      max_retries: 0,
      reasoning_effort: 'medium',
    });

    if (!Array.isArray(content.signals) || content.signals.length !== 5) {
      throw new Error(`score returned ${content.signals?.length ?? 0} signals (expected 5)`);
    }

    const sanitizedContent = sanitizeInterestEvidence(content);
    const interestScore = sanitizedContent.signals.reduce(
      (sum, s) => sum + Math.max(0, Math.min(20, s.score)),
      0
    );
    const matchScore = cand.match_score ?? 0;
    const cohort = assignCohort(matchScore, interestScore);

    await supabase
      .from('candidates')
      .update({
        interest_score: interestScore,
        interest_evidence: sanitizedContent,
        cohort,
      })
      .eq('id', candidateId);

    return NextResponse.json({ interest_score: interestScore, cohort });
  } catch (e) {
    const message = (e as Error).message;
    const profile = cand.profile_json as CandidateProfile;
    const transcript = turns.map((t) => ({
      turn_number: t.turn_number,
      speaker: t.speaker,
      content: t.content,
    }));
    const content = sanitizeInterestEvidence(buildFallbackInterestEvidence(profile, transcript));
    const interestScore = content.signals.reduce(
      (sum, signal) => sum + Math.max(0, Math.min(20, signal.score)),
      0
    );
    const matchScore = cand.match_score ?? 0;
    const cohort = assignCohort(matchScore, interestScore);

    await supabase
      .from('candidates')
      .update({
        interest_score: interestScore,
        interest_evidence: content,
        cohort,
      })
      .eq('id', candidateId);
    console.warn(`[score] model failed for ${candidateId}; used fallback score: ${message}`);
    return NextResponse.json({ interest_score: interestScore, cohort, fallback: true });
  }
}
